- name: Download latexmk
  get_url: "url={{ latexmk_src }} dest=/usr/local/bin/latexmk" 

- name: Setup ownership latexmk
  command: chown {{ latexmk_usr }} /usr/local/bin/latexmk
  when: latexmk is defined

- name: Update permissions  
  command: chmod a+x /usr/local/bin/latexmk